app/models.py
__author__ = 'xuqiangqiang'
# coding:utf-8

from app import db

class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer,primary_key=True)
    name = db.Column(db.String(64),unique=True)
    users = db.relationship('User',backref='role')

    def __repr__(self):
        return '<Role %r>' % self.name


class User(db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(64),unique=True,index=True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))

    def __repr__(self):
        return '<User %r>' % self.username

app/main/forms.py
__author__ = 'xuqiangqiang'
# coding:utf-8

from flask.ext.wtf import Form
from wtforms import StringField,SubmitField
from wtforms.validators import DataRequired

class NameForm(Form):
    name = StringField('What is your name?',validators=[DataRequired()])
    submit = SubmitField('sublit')

app/__init__.py
__author__ = 'xuqiangqiang'
# coding:utf-8

from flask import Flask
from config import config
from flask.ext.bootstrap import Bootstrap
from flask.ext.sqlalchemy import SQLAlchemy


db = SQLAlchemy()
bootstrap = Bootstrap()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    bootstrap.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return  app

app/main/__init__.py
__author__ = 'xuqiangqiang'
# coding:utf-8

from flask import Blueprint

main = Blueprint('main',__name__)

from . import views, errors

app/main/views.py
__author__ = 'xuqiangqiang'
# coding:utf-8

from flask import render_template,redirect,session,url_for
from . import main
from .forms import NameForm
from .. import  db
from ..models import User

@main.route('/',methods=['GET','POST'])
def index():
    form = NameForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.name.data).first()
        if user is None:
            user = User(username=form.name.data)
            db.session.add(user)
            db.session.commit()
            session['know'] = False
        else:
            session['know'] = True
        session['name'] = form.name.data
        form.name.data = ''
        return redirect(url_for('main.index'))
    return  render_template('index.html',form=form,name=session.get('name'),know=session.get('know',False))


@main.route('/data2')
def ceshi():
    data = 'Dota2'
    return render_template('ceshi.html',name=data)

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
             data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
            </ul>
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.ceshi') }}">Dota2</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
    <div class="container">
        {% block page_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/ceshi.html
{% extends "base.html" %}

{% block page_content %}
    <div class="page-header">
        <h1>Hello  {{ name }}</h1>
    </div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
{#    <div class="container">#}
{#        {% for message in get_flashed_messages() %}#}
{#            <div class="alert alert-warning">#}
{#                  {{ message }}#}
{#            </div>#}
{#        {% endfor %}#}
{#    </div>#}
    <div class="page-header">
        <h1>Hello, {% if name %}{{ name }}{% else %}stranger{% endif %}</h1>
        {% if not know %}
    <div class="alert alert-warning">
        Please to meet you!
    </div>
        {% else %}
    <div class="alert alert-warning">
        Happy to see you again!
    </div>
    {% endif %}
    </div>
      <form action="" method="POST">
        {{ wtf.quick_form(form) }}
      </form>
{% endblock %}